# Generated by Django 4.0.4 on 2022-05-17 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Name must be greater than 2 characters.')])),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
